### masking

In [1]:
import numpy as np

In [2]:
names = np.array(["bob","joe","will","bob","will","joe","joe"])
data=np.random.randn(7,4)
print(names,names.ndim)
print(data,data.ndim)

['bob' 'joe' 'will' 'bob' 'will' 'joe' 'joe'] 1
[[-0.39520166  0.61103607 -0.33492754  0.84529065]
 [-1.55515052  0.28116476  0.06333613 -0.63861272]
 [ 0.23485324 -0.89210651 -2.2565923  -0.38005703]
 [-1.03407461 -0.97121414  0.8277412  -1.89170257]
 [-0.91144377  2.43267553 -0.26981134 -0.76029326]
 [ 0.44947754  0.10070822  1.13691817  1.60177703]
 [ 0.98504311 -1.70545438 -0.14435768 -0.836262  ]] 2


In [3]:
names=="bob"

array([ True, False, False,  True, False, False, False])

In [4]:
data[names=="bob"]

array([[-0.39520166,  0.61103607, -0.33492754,  0.84529065],
       [-1.03407461, -0.97121414,  0.8277412 , -1.89170257]])

In [5]:
data[names=="bob",2:]

array([[-0.33492754,  0.84529065],
       [ 0.8277412 , -1.89170257]])

In [6]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
print(a[a < 5])


[1 2 3 4]


In [8]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [9]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [10]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [13]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [14]:
five_up = (a > 5) | (a == 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [15]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [16]:
# Using generators:

- np.fromiter(iterable, datatype)

In [17]:
iterable = (x*x for x in range(5) for y in range(10) if y<x)
#print(iterable)
np.fromiter(iterable, float)

array([ 1.,  4.,  4.,  9.,  9.,  9., 16., 16., 16., 16.])

In [18]:
iterable = (x*x for x in range(5) for y in range(10) if y<x)

np.fromiter(iterable, int)

array([ 1,  4,  4,  9,  9,  9, 16, 16, 16, 16])

In [22]:
arr = np.array([1,2,3,89,45,23,12,13,26])
k=35
np.where(arr<k)

(array([0, 1, 2, 5, 6, 7, 8], dtype=int64),)

In [20]:
arr = np.array([1,2,3,89,45,23,12,13,26])
arr[np.where(arr<35)]

array([ 1,  2,  3, 23, 12, 13, 26])

In [23]:
np.nonzero(arr < k)

(array([0, 1, 2, 5, 6, 7, 8], dtype=int64),)

### Aggregate and Statistical Functions

In [24]:
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)

arr2 = np.array([[0, 10, 20], [30, 40, 50], [60, 70, 80]])
print(arr2)

arr3 = np.array([[14, 6, 9, -12, 19, 72],[-9, 8, 22, 0, 99, -11]])
print(arr3)

[10 20 30 40 50]
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]
[[ 14   6   9 -12  19  72]
 [ -9   8  22   0  99 -11]]


In [25]:
print(arr1.sum())
print(arr2.sum())
print(arr3.sum())

150
360
217


In [26]:
print(arr2.sum(axis = 0))
arr3.sum(axis = 0)

[ 90 120 150]


array([  5,  14,  31, -12, 118,  61])

In [27]:
print(arr2.sum(axis = 1))
arr3.sum(axis = 1)

[ 30 120 210]


array([108, 109])

In [28]:
print(arr2.sum(0))
print(arr2.sum(1))
print(arr3.sum(1))
arr3.sum(0)

[ 90 120 150]
[ 30 120 210]
[108 109]


array([  5,  14,  31, -12, 118,  61])

In [29]:
#Python NumPy average
print(np.average(arr1))
print(np.average(arr2))
np.average(arr3)

30.0
40.0


18.083333333333332

In [30]:
print(np.average(arr2, axis = 0))
np.average(arr2, axis = 1)

[30. 40. 50.]


array([10., 40., 70.])

In [31]:
print(np.average(arr2, 0))
np.average(arr2, 1)

[30. 40. 50.]


array([10., 40., 70.])

In [32]:

print(np.prod(arr1))
np.prod(arr2) # any number multiply by zero gives zero

12000000


0

In [33]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.prod(x))

y = np.random.randint(1, 10, size = (5, 5))
np.prod(y)

720


-415236096

In [34]:
print(np.prod(x, axis = 0))
print(np.prod(x, axis = 1))
print(np.prod(y, axis = 0))
print(np.prod(y, axis = 1))

[ 4 10 18]
[  6 120]
[12096    90   135  3584  1344]
[ 128  480  288 5292 7560]


In [35]:
print(arr1.min())
print(arr2.min())
print(arr3.min())

10
0
-12


In [36]:
print(arr1.min(axis=0))
print(arr2.min(1))
print(arr3.min(0))

10
[ 0 30 60]
[ -9   6   9 -12  19 -11]


In [37]:
print(arr1.max(axis=0))
print(arr2.max(1))
print(arr3.max(0))

50
[20 50 80]
[14  8 22  0 99 72]


In [38]:
print(arr1.mean())
print(arr2.mean())
print(arr3.mean())

30.0
40.0
18.083333333333332


In [39]:
print(arr1.mean(axis=0))
print(arr2.mean(1))
print(arr3.mean(0))

30.0
[10. 40. 70.]
[ 2.5  7.  15.5 -6.  59.  30.5]


In [40]:
np.median(arr1)
np.median(arr2)
np.median(arr3)

# Median of x and Y axis
np.median(arr2, axis = 0)
np.median(arr2, axis = 1)

array([10., 40., 70.])

In [41]:
#Formula of Python Nampy var is : (item1 – mean)2 + …(itemN – mean)2 / total items
print(arr1.var(),"var")
arr2.var()
arr3.var()

x.var()
y.var()

200.0 var


6.742399999999999

In [42]:
#Python NumPy std
#The Python NumPy std function returns the standard deviation of a given array or in a given axis. The formula behind this is the square root of variance.


print(arr1.std())
print(arr2.std())
print(arr3.std())

14.142135623730951
25.81988897471611
32.44086500422303


In [43]:
#Python NumPy cumsum
#The Python Numpy cumsum function returns the cumulative sum of a given array or in a given axis.
print(arr1.cumsum())
arr2.cumsum()

[ 10  30  60 100 150]


array([  0,  10,  30,  60, 100, 150, 210, 280, 360], dtype=int32)

In [44]:
print(arr2.cumsum(axis = 0))
arr2.cumsum(axis = 1)

[[  0  10  20]
 [ 30  50  70]
 [ 90 120 150]]


array([[  0,  10,  30],
       [ 30,  70, 120],
       [ 60, 130, 210]], dtype=int32)

In [45]:
print(arr1.cumprod())
arr2.cumprod()

[      10      200     6000   240000 12000000]


array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [46]:
#Python NumPy argmin
#The Python NumPy argmin returns the index position of the minimum value in a given array 
#or a given axis. To demonstrate this and the next function, 
#we declared two more arrays of random values



In [52]:
arr4 = np.random.randint(9, size = (9))
print(arr4)

arr5 = np.random.randint(25, size = (5, 5))
arr5

[2 6 5 7 2 2 0 1 7]


array([[11,  5, 24,  4,  7],
       [ 4, 13, 23, 11, 16],
       [14,  3,  9,  8,  4],
       [ 7, 18, 16, 21, 16],
       [ 4, 20, 23, 14,  8]])

In [53]:
arr4.argmin()# index

6

In [54]:
a = arr4.argmin()
arr4[a]

0

In [55]:
arr5.argmin(axis = 0)

array([1, 2, 2, 0, 2], dtype=int64)

In [51]:
arr5.argmin(axis = 1)

array([2, 2, 4, 0, 3], dtype=int64)

In [56]:
arr4.argmax()

3

In [57]:
arr3.argmax(axis = 0)

array([0, 1, 1, 1, 1, 0], dtype=int64)

In [58]:
#Python NumPy corrcoef
#Python NumPy corrcoef function find and returns the correlation coefficient of an array. 



Correlation coefficients are used in statistics to measure how strong a relationship is between two variables. There are several types of correlation coefficient, but the most popular is Pearson’s. Pearson’s correlation (also called Pearson’s R) is a correlation coefficient commonly used in linear regression. If you’re starting out in statistics, you’ll probably learn about Pearson’s R first. In fact, when anyone refers to the correlation coefficient, they are usually talking about Pearson’s.





Correlation coefficient formulas are used to find how strong a relationship is between data. The formulas return a value between -1 and 1, where:

1 indicates a strong positive relationship.
-1 indicates a strong negative relationship.
A result of zero indicates no relationship at all.

In [59]:
np.corrcoef(arr1)

1.0

In [60]:
np.corrcoef(arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.corrcoef(arr3)

array([[ 1.        , -0.12768134],
       [-0.12768134,  1.        ]])

### Saving data

In [62]:
import numpy as np
data = np.linspace(0,1,201)

In [63]:
np.savetxt('A_data.dat', data)

In [64]:
x = np.linspace(0, 1, 201)
y = np.random.random(201)

np.savetxt('AA_data.dat', [x, y])

In [65]:
data = np.column_stack((x, y))
np.savetxt('AA_data.dat', data)

In [66]:
header = "X-Column, Y-Column"
np.savetxt('AB_data.dat', data, header=header)


In [67]:
header = "X-Column, Y-Column\n"
header += "This is a second line"
np.savetxt('AB_data.dat', data, header=header)

- Loading Saved Data with Numpy

In [68]:
data = np.loadtxt('AB_data.dat')
x = data[:, 0]
y = data[:, 1]

In [69]:
print(x)

[0.    0.005 0.01  0.015 0.02  0.025 0.03  0.035 0.04  0.045 0.05  0.055
 0.06  0.065 0.07  0.075 0.08  0.085 0.09  0.095 0.1   0.105 0.11  0.115
 0.12  0.125 0.13  0.135 0.14  0.145 0.15  0.155 0.16  0.165 0.17  0.175
 0.18  0.185 0.19  0.195 0.2   0.205 0.21  0.215 0.22  0.225 0.23  0.235
 0.24  0.245 0.25  0.255 0.26  0.265 0.27  0.275 0.28  0.285 0.29  0.295
 0.3   0.305 0.31  0.315 0.32  0.325 0.33  0.335 0.34  0.345 0.35  0.355
 0.36  0.365 0.37  0.375 0.38  0.385 0.39  0.395 0.4   0.405 0.41  0.415
 0.42  0.425 0.43  0.435 0.44  0.445 0.45  0.455 0.46  0.465 0.47  0.475
 0.48  0.485 0.49  0.495 0.5   0.505 0.51  0.515 0.52  0.525 0.53  0.535
 0.54  0.545 0.55  0.555 0.56  0.565 0.57  0.575 0.58  0.585 0.59  0.595
 0.6   0.605 0.61  0.615 0.62  0.625 0.63  0.635 0.64  0.645 0.65  0.655
 0.66  0.665 0.67  0.675 0.68  0.685 0.69  0.695 0.7   0.705 0.71  0.715
 0.72  0.725 0.73  0.735 0.74  0.745 0.75  0.755 0.76  0.765 0.77  0.775
 0.78  0.785 0.79  0.795 0.8   0.805 0.81  0.815 0.

In [70]:
## array to string
x = np.array([1e-16,1,2,3,5e-9])
np.array2string(x, precision=8, separator=',',
                      suppress_small=True)

'[0.        ,1.        ,2.        ,3.        ,0.00000001]'

In [71]:
x  = np.arange(3.)
np.array2string(x, formatter={'float':lambda x: "%.2f" % x})

'[0.00 1.00 2.00]'

In [72]:
x  = np.arange(3)
np.array2string(x, formatter={'int':lambda x: hex(x)})

'[0x0 0x1 0x2]'

In [73]:
np.array_str(np.arange(3))


'[0 1 2]'

In [74]:
hex(67)

'0x43'

## Pandas

### Pandas :
- Pandas is a library in python which is used to perform data anlysis.
- Pandas will reduce comlexity and make our work very easy.
- It can be applicable for any type of data(ordered or unordered)
- The ouput will be in the format of tabular form.That tabular form is named as DataFrame.
- This can be applied for different file formats like csv,excel,pdf,json and etc.
- Main Key words in creating our data using pandas:
### Series:

- This series is a 1-d array.
- The output will be in the format of row by row(line to line).
#### Data Frame:

- In this the data will be represented in the format of rows and columns in a tabular arrangement
- Importing the Pandas library:

In [75]:
import pandas as pd
import numpy as np

In [76]:
### Creating data using Series:
### pd.Series(list)

a = pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [77]:
### Creating Series using Numpy array:
### pd.Series(np.array(list))

a = pd.Series(np.array([1,2,3,4]))
a

0    1
1    2
2    3
3    4
dtype: int32

In [78]:
### Creating Data Series using Dictionary:

d = {'a' : 0,"b" : 1,"c" : 2}
d

{'a': 0, 'b': 1, 'c': 2}

In [79]:
a = pd.Series(d)
a

a    0
b    1
c    2
dtype: int64

In [80]:
b = pd.Series({'a' : 0,"b" : 1,"c" : 2})
b

a    0
b    1
c    2
dtype: int64

In [81]:
### changing the index values in series:

a = pd.Series([1,2,3,45],index = ['z','x','y','a'])
a

z     1
x     2
y     3
a    45
dtype: int64

In [82]:
a = pd.Series([1,2,'a',45,6],index = np.arange(1,6))
a

1     1
2     2
3     a
4    45
5     6
dtype: object

In [83]:
a.dtype  ### o --- object datatype --> combination of numbers and alphabets.

dtype('O')