## Numpy

-  Numerical Python, popularly known as Numpy has been designed to carry out mathematical computations at a faster and easier rate. 
- Numpy provides a large library of high level mathematical functions to operate on these structures.
- data structures like multi dimensional arrays beyond matrices and linear arrays. 

- In command line            
    - pip install numpy 
- Anaconda distribution            
    - conda install numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


- General Programming Concepts
    - Data Types, Type Conversion, Operators
    - Conditional Statements and Loops
    - Lists, Tuples, Sets, Dictionaries
    - Functions
    - OOPs in Python
    - Functional Programming i.e. List, Set and Dictionary Comprehensions

- If we are going to work on Data Fields like
    - Data Analytics
    - Machine Learning
    - AI
    - Deep Learning
    - Field in Data

In [2]:
import numpy as np

In [3]:
np.__version__

'1.16.2'

In [4]:
arr = np.array([1,2,2])
type(arr)

numpy.ndarray

In [5]:
arr.ndim

1

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr1 = np.array([1,2,2,2.3,"alekhya"])
type(arr)

numpy.ndarray

In [8]:
arr1.dtype

dtype('<U32')

In [9]:
arr3 = np.array("24-07-20200")
arr3.dtype

dtype('<U11')

- 'b' − boolean
- 'i' − (signed) integer
- 'u' − unsigned integer
- 'f' − floating-point
- 'c' − complex-floating point
- 'm' − timedelta
- 'M' − datetime
- 'O' − (Python) objects
- 'S', 'a' − (byte-)string
- 'U' − Unicode
- 'V' − raw data (void)

In [10]:
a = np.array(3+2j)
a.dtype

dtype('complex128')

In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1,10.5)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
range(1,10.5)

TypeError: 'float' object cannot be interpreted as an integer

In [104]:
a = np.arange(1,10.5,1.2)
a

array([1. , 2.2, 3.4, 4.6, 5.8, 7. , 8.2, 9.4])

In [105]:

a.shape

(8,)

In [106]:
a.size

8

In [21]:
f.reshape(5,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [107]:
f.size

50

In [22]:
f.reshape(2,-1)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39, 41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81,
        83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [23]:
f.reshape(-1,4)

ValueError: cannot reshape array of size 50 into shape (4)

In [24]:
f1 = f.reshape(-1,5)
f1

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [25]:
f1.shape

(10, 5)

In [26]:
f1.ndim

2

In [27]:
arr4 = np.arange(0,20).reshape(2,2,5)
arr4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [28]:
arr4.ndim

3

In [29]:
arr = arr4.reshape(-1,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
arr.ndim

2

In [52]:
np.linspace(0, 10, 100)



array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [54]:
x = np.ones(2, dtype=np.int)
x

array([1, 1])

In [55]:
x = np.ones(2, dtype=np.float)
x

array([1., 1.])

In [56]:
x = np.ones(2, dtype=np.object)
x

array([1, 1], dtype=object)

In [57]:
y = np.ones((10,2),dtype=int)
print(y)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [58]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [67]:
zero = np.zeros((3,3),dtype=object)
print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Adding and sorting elements¶

In [70]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8,6])

In [71]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 6, 7, 8])

In [83]:
a = np.array([3, 4, 2, 1,34,6,17,45,22,78])
np.partition(a,1)

array([ 1,  2,  4,  3, 34,  6, 17, 45, 22, 78])

In [92]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0], dtype=int64)

In [93]:
[surnames[i] + ", " + first_names[i] for i in ind]

['Galilei, Galileo', 'Hertz, Gustav', 'Hertz, Heinrich']

In [94]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [95]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [103]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[1,21]])
x,y

(array([[1, 2],
        [3, 4]]), array([[ 5,  6],
        [ 1, 21]]))

In [100]:
np.concatenate((x, y), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 1, 21]])

In [101]:
np.concatenate((x, y), axis=1)

array([[ 1,  2,  5,  6],
       [ 3,  4,  1, 21]])

### Masking

In [108]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [110]:
print(a[a < 5])


[1 2 3 4]


In [111]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [112]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


- Or you can select elements that satisfy two conditions using the & and | operators:

In [114]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [115]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [116]:
five_up =a[(a > 5) | (a == 5)]
print(five_up)

[ 5  6  7  8  9 10 11 12]


### Indexing

In [15]:
f = np.arange(1,100,2)
f

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [16]:
f[1:20]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39])

In [17]:
f[8]

17

In [33]:
f[::-1]

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67,
       65, 63, 61, 59, 57, 55, 53, 51, 49, 47, 45, 43, 41, 39, 37, 35, 33,
       31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [36]:
f[-10:-1]

array([81, 83, 85, 87, 89, 91, 93, 95, 97])

In [35]:
f[-10:]

array([81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [118]:
a1 = np.array([[1, 1],
...                [2, 2]])

a2 = np.array([[3, 3],
...                [4, 4]])

In [119]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [120]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [121]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [123]:
np.hsplit(x, 2)

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]), array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [126]:
np.vsplit(x, 1)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [128]:
a = np.vsplit(x, 2)
a

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [129]:
a[0]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [130]:
a[1]

array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

### Math
- Arithmetic Functions

In [ ]:
a = np.array([1,2,3])
b = np.array([5,6,7])
print(a+b)
print(a-b)
print(a/b)
print(a%b)
print(a//b)
a*b

In [31]:
a = np.array([10,20,30])
b= np.array([2,3,4])
print("division of a and b :",np.divide(a,b))
print("true division of a  :",np.true_divide(a,b))
print("floor_division of a and b :",np.floor_divide(a,b))
print("float_power of a raised to b :",np.float_power(a,b))
print("fmod of a and b :",np.fmod(a,b))
print("mod of a and b :",np.mod(a,b))
print("quotient and remainder of a and b :",np.divmod(a,b))
print("remainders when a/b :",np.remainder(a,b))

division of a and b : [5.         6.66666667 7.5       ]
true division of a  : [5.         6.66666667 7.5       ]
floor_division of a and b : [5 6 7]
float_power of a raised to b : [1.0e+02 8.0e+03 8.1e+05]
fmod of a and b : [0 2 2]
mod of a and b : [0 2 2]
quotient and remainder of a and b : (array([5, 6, 7], dtype=int32), array([0, 2, 2], dtype=int32))
remainders when a/b : [0 2 2]


In [134]:
a.sum()

6

In [135]:
a = np.array([[1,2],[5,6]])
a.sum()

14

In [136]:
a.sum(axis=0)

array([6, 8])

In [137]:
a.sum(axis=1)

array([ 3, 11])

- Trigonometric Functions

In [40]:
import numpy as np 
import math 
  
in_array = [0, math.pi / 2, np.pi / 3, np.pi] 
print ("Radian values : \n", in_array) 
  
degree_Values = np.degrees(in_array) 
print ("\nDegree values : \n", degree_Values) 

Radian values : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Degree values : 
 [  0.  90.  60. 180.]


In [41]:
import numpy as np 
import math 
  
in_array = [0, math.pi / 2, np.pi / 3, np.pi] 
print ("Radian values : \n", in_array) 
  
out_Values = np.rad2deg(in_array) 
print ("\nDegree values : \n", out_Values) 

Radian values : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Degree values : 
 [  0.  90.  60. 180.]


In [42]:
import numpy as np 
import math 
  
degree = np.arange(10.) * 90
print ("Degree values : \n", degree) 
  
radian = np.deg2rad(degree) 
print ("\nradian values : \n", radian) 

Degree values : 
 [  0.  90. 180. 270. 360. 450. 540. 630. 720. 810.]

radian values : 
 [ 0.          1.57079633  3.14159265  4.71238898  6.28318531  7.85398163
  9.42477796 10.99557429 12.56637061 14.13716694]


In [43]:
x = np.sin(np.pi/2)

print(x)

1.0


In [45]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)
x

array([1.        , 0.8660254 , 0.70710678, 0.58778525])

In [46]:
arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [47]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


- Logarithmic and Exponential Functions

In [ ]:
exp(arr)	Returns exponential of an input array element wise
expm1(arr)	Returns exponential exp(x)-1 of an input array element wise
exp2(arr)	Returns exponential 2**x of all elements in an array
log(arr)	Returns natural log of an input array element wise
log10(arr)	Returns log base 10 of an input array element wise
log2(arr)	Returns log base 2 of an input array element wise
logaddexp(arr)	Returns logarithm of the sum of exponentiations of all inputs
logaddexp2(arr)	Returns logarithm of the sum of exponentiations of the inputs in base 2

In [37]:
import numpy as np
a = np.array([1,2,3,4,5])
a_log = np.log(a)
a_exp = np.exp(a)
print("log of input array a is:",a_log)
print("exponent of input array a is:",a_exp)

log of input array a is: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
exponent of input array a is: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


- Rounding Functions

In [ ]:
around(arr,decimal)	Rounds the elements of an input array upto given decimal places
round_(arr,decimal)	Rounds the elements of an input array upto given decimal places
rint(arr)	Round the elements of an input array to the nearest integer towards zero
fix(arr)	Round the elements of an input array to the nearest integer towards zero
floor(arr)	Returns floor of input array element wise
ceil(arr)	Returns ceiling of input array element wise
trunc(arr)	Return the truncated value of an input array element wise

In [38]:
a = np.array([1.23,4.165,3.8245])
rounded_a = np.round_(a,2)
print(rounded_a)

[1.23 4.16 3.82]


In [39]:
floor_a = np.floor(a)
print(floor_a)

[1. 4. 3.]


In [ ]:
- Miscellaneous Functions
sqrt(arr)	Returns the square root of an input array element wise
cbrt(arr)	Returns cube root of an input array element wise
absolute(arr)	Returns absolute value each element in an input array
maximum(arr1,arr2,…)	Returns element wise maximum of the input arrays
minimum(arr1,arr2,…)	Returns element wise minimum of the input arrays
interp(arr, xp, fp)	Calculates one-dimensional linear interpolation
convolve(arr, v)	Returns linear convolution of two one-dimensional sequences
clip(arr, arr_min, arr_max)	Limits the values in an input array

##### Random Concept

In [1]:
from numpy import random


In [2]:
x = random.randint(100) #Generate a random integer from 0 to 100

print(x)

34


In [6]:
x = random.rand()#Generate a random float from 0 to 1

print(x)

0.5342193118102847


In [7]:
x = random.rand(20)#Generate a random float from 0 to 1

print(x)

[0.34509769 0.32140195 0.32745326 0.56654645 0.66044548 0.87807959
 0.82840808 0.07744634 0.67452052 0.65068167 0.58542936 0.89196217
 0.43829981 0.04746203 0.91320949 0.89048812 0.36083455 0.23321078
 0.26419643 0.84884557]


In [8]:
x=random.randint(100, size=(5))#Generate a 1-D array containing 5 random integers from 0 to 100

print(x)

[15 64 85 63 45]


In [12]:
x=random.randint(100)#Generate a 1-D array containing 5 random integers from 0 to 100

print(x)

41


In [13]:
x = random.randint(100, size=(3, 5))#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

print(x)

[[62 40 40 72 48]
 [75 43 33  5 46]
 [92 80 51  9 69]]


In [14]:
x = random.rand(5)#Generate a 1-D array containing 5 random floats

print(x)

[0.69151092 0.56759673 0.85357018 0.60327693 0.47782253]


In [15]:
#Generate a 2-D array with 3 rows, each row containing 5 random numbers:



x = random.rand(3, 5)

print(x)

[[0.47209173 0.36348604 0.33990269 0.72394416 0.66412772]
 [0.23811545 0.00788732 0.32014328 0.46715503 0.98138472]
 [0.11668904 0.33761196 0.26301165 0.64552231 0.77303389]]


In [16]:
#Return one of the values in an array:



x = random.choice([3, 5, 7, 9])

print(x)

9


In [17]:
#Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):



x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 5 3 3 3]
 [9 5 9 5 5]
 [3 7 3 9 9]]


#### Random Distribution

- A random distribution is a set of random numbers that follow a certain probability density function.

#### Probability Density Function: A function that describes a continuous probability. i.e. probability of all values in an array.
- Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

- The probability for the value to be 3 is set to be 0.1

- The probability for the value to be 5 is set to be 0.3

- The probability for the value to be 7 is set to be 0.6

- The probability for the value to be 9 is set to be 0

In [18]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 7 7 7 5 3 7 7 5 7 5 7 7 7 3 7 5 5 7 7 5 7 5 7 7 7 7 7 7 7 5 5 7 7 7
 7 7 7 5 7 7 7 5 3 5 5 5 7 7 3 5 7 7 5 5 5 5 5 7 7 7 5 5 7 7 7 7 5 7 5 5 7
 3 3 7 7 7 5 7 5 5 7 5 7 7 5 5 5 7 5 5 7 7 7 3 5 5 7]


In [19]:
#Same example as above, but return a 2-D array with 3 rows, each containing 5 values.



x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)


[[5 7 7 7 7]
 [5 5 3 7 7]
 [5 7 7 5 7]]


##### Random Permutations of Elements
- A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

- The NumPy Random module provides two methods for this: shuffle() and permutation().



In [ ]:
shuffle(...) method of mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8]
    
    Multi-dimensional arrays are only shuffled along the first axis:
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random.shuffle(arr)
    >>> arr
    array([[3, 4, 5],
           [6, 7, 8],
           [0, 1, 2]])

In [21]:
#Shuffling Arrays
#Shuffle means changing arrangement of elements in-place. i.e. in the array itself.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[1 3 5 4 2]


In [22]:
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[1 5 2 3 4]


In [25]:
help(np.random.permutation)

Help on built-in function permutation:

permutation(...) method of mtrand.RandomState instance
    permutation(x)
    
    Randomly permute a sequence, or return a permuted range.
    
    If `x` is a multi-dimensional array, it is only shuffled along its
    first index.
    
    Parameters
    ----------
    x : int or array_like
        If `x` is an integer, randomly permute ``np.arange(x)``.
        If `x` is an array, make a copy and shuffle the elements
        randomly.
    
    Returns
    -------
    out : ndarray
        Permuted sequence or array range.
    
    Examples
    --------
    >>> np.random.permutation(10)
    array([1, 7, 4, 3, 0, 9, 2, 5, 8, 6])
    
    >>> np.random.permutation([1, 4, 9, 12, 15])
    array([15,  1,  9,  4, 12])
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random.permutation(arr)
    array([[6, 7, 8],
           [0, 1, 2],
           [3, 4, 5]])



In [ ]:
Normal Distribution
binomial 
poission
logistic

In [27]:
print(dir(random))

['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']
