## Numpy

-  Numerical Python, popularly known as Numpy has been designed to carry out mathematical computations at a faster and easier rate. 
- Numpy provides a large library of high level mathematical functions to operate on these structures.
- data structures like multi dimensional arrays beyond matrices and linear arrays. 

- In command line            
    - pip install numpy 
- Anaconda distribution            
    - conda install numpy

In [98]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


- General Programming Concepts
    - Data Types, Type Conversion, Operators
    - Conditional Statements and Loops
    - Lists, Tuples, Sets, Dictionaries
    - Functions
    - OOPs in Python
    - Functional Programming i.e. List, Set and Dictionary Comprehensions

- If we are going to work on Data Fields like
    - Data Analytics
    - Machine Learning
    - AI
    - Deep Learning
    - Field in Data

In [1]:
import numpy as np

In [3]:
np.__version__

'1.16.2'

In [2]:
a = np.array([1,2,3])

In [4]:
a.ndim

1

In [5]:
a.dtype


dtype('int32')

In [6]:
b = np.array([1,2.3,"a"])

In [8]:
b.dtype

dtype('<U32')

In [9]:
arr3 = np.array("24-07-20200")
arr3.dtype

dtype('<U11')

- 'b' − boolean
- 'i' − (signed) integer
- 'u' − unsigned integer
- 'f' − floating-point
- 'c' − complex-floating point
- 'm' − timedelta
- 'M' − datetime
- 'O' − (Python) objects
- 'S', 'a' − (byte-)string
- 'U' − Unicode
- 'V' − raw data (void)

In [10]:
a = np.array(3+2j)
a.dtype

dtype('complex128')

In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1,10.5)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
range(1,10.5)

TypeError: 'float' object cannot be interpreted as an integer

In [14]:
a = np.arange(1,10.5,1.2)
a

array([1. , 2.2, 3.4, 4.6, 5.8, 7. , 8.2, 9.4])

In [15]:
a.shape

(8,)

In [16]:
a.size

8

In [17]:
f = np.arange(1,51)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [18]:
f.reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [19]:
f.size

50

In [20]:
f.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [21]:
f.reshape(-1,4)

ValueError: cannot reshape array of size 50 into shape (4)

In [22]:
f1 = f.reshape(-1,5)
f1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [23]:
f1.shape

(10, 5)

In [25]:
f1.ndim

2

In [26]:
arr4 = np.arange(0,50).reshape(5,1,10)
arr4

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]])

In [27]:
arr4 = np.arange(0,50).reshape(5,2,5)
arr4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [28]:
arr4.ndim

3

In [31]:
arr = arr4.reshape(-1,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [32]:
arr.ndim

2

In [33]:
np.linspace(0, 10, 100)



array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [34]:
x = np.ones(2, dtype=np.int)
x

array([1, 1])

In [35]:
x = np.ones(2, dtype=np.float)
x

array([1., 1.])

In [36]:
x = np.ones(2, dtype=np.object)
x

array([1, 1], dtype=object)

In [37]:
y = np.ones((10,2),dtype=int)
print(y)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [40]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [41]:
zero = np.zeros((3,3),dtype=object)
print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Adding and sorting elements¶

In [42]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8,6])

In [43]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 6, 7, 8])

In [44]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0], dtype=int64)

In [45]:
[surnames[i] + ", " + first_names[i] for i in ind]

['Galilei, Galileo', 'Hertz, Gustav', 'Hertz, Heinrich']

In [46]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [47]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[1,21]])
x,y

(array([[1, 2],
        [3, 4]]), array([[ 5,  6],
        [ 1, 21]]))

In [49]:
np.concatenate((x, y), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 1, 21]])

In [50]:
np.concatenate((x, y), axis=1)

array([[ 1,  2,  5,  6],
       [ 3,  4,  1, 21]])

### Indexing

In [51]:
f = np.arange(1,100,2)
f

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [52]:
f[1:20]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39])

In [53]:
f[8]

17

In [54]:
f[::-1]

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67,
       65, 63, 61, 59, 57, 55, 53, 51, 49, 47, 45, 43, 41, 39, 37, 35, 33,
       31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [55]:
f[-10:-1]

array([81, 83, 85, 87, 89, 91, 93, 95, 97])

In [56]:
f[-10:]

array([81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [110]:
s = np.array([[1,2,3],[4,5,6],[7,8,9]])
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
s[:2,:1]

array([[1],
       [4]])

In [112]:
s[:2,1:]

array([[2, 3],
       [5, 6]])

In [57]:
a1 = np.array([[1, 1],
...                [2, 2]])

a2 = np.array([[3, 3],
...                [4, 4]])

In [58]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [59]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [60]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [61]:
np.hsplit(x, 2)

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]), array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [62]:
np.vsplit(x, 1)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [63]:
a = np.vsplit(x, 2)
a

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [64]:
a[0]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
a[1]

#### Boolean indexing

In [121]:
names = np.array(["bob","joe","will","bob","will","joe","joe"])
data=np.random.randn(7,4)
print(names,names.ndim)
print(data,data.ndim)

['bob' 'joe' 'will' 'bob' 'will' 'joe' 'joe'] 1
[[-0.39831536 -1.32651053 -0.53202895  0.912466  ]
 [ 0.6018626  -1.47228513  1.1160726   0.47265358]
 [-0.04155883 -0.98079004  0.19548743 -0.00595813]
 [ 0.12604313 -0.65954548 -0.43223043  0.97403264]
 [ 0.84200105  0.58991585 -0.33247246  0.40397555]
 [-0.58097591  1.4978003   1.29275085 -0.54533185]
 [-0.93256787  0.33112934  0.063649   -0.85700002]] 2


In [122]:
names=="bob"

array([ True, False, False,  True, False, False, False])

In [123]:
data[names=="bob"]

array([[-0.39831536, -1.32651053, -0.53202895,  0.912466  ],
       [ 0.12604313, -0.65954548, -0.43223043,  0.97403264]])

In [124]:
data[names=="bob",2:]

array([[-0.53202895,  0.912466  ],
       [-0.43223043,  0.97403264]])

In [134]:
## Fancy indexing

In [126]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [129]:
arr[[1,2,3,4],[0,2,3,1]]

array([ 4, 10, 15, 17])

In [133]:
arr[[-3,-5,-8],[-1,-2,-1]]

array([23, 14,  3])

## transposing arrays and swappingaxes 

In [138]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [139]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [141]:
s = np.arange(16).reshape((2,2,4))
s

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [142]:
s.T


array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [144]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [147]:
arr.swapaxes(0,1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Math
- Arithmetic Functions

In [66]:
a = np.array([1,2,3])
b = np.array([5,6,7])
print(a+b)
print(a-b)
print(a/b)
print(a%b)
print(a//b)
a*b

[ 6  8 10]
[-4 -4 -4]
[0.2        0.33333333 0.42857143]
[1 2 3]
[0 0 0]


array([ 5, 12, 21])

In [67]:
a = np.array([10,20,30])
b= np.array([2,3,4])
print("division of a and b :",np.divide(a,b))
#print("true division of a  :",np.true_divide(a,b))
print("floor_division of a and b :",np.floor_divide(a,b))
#print("float_power of a raised to b :",np.float_power(a,b))
#print("fmod of a and b :",np.fmod(a,b))
print("mod of a and b :",np.mod(a,b))
print("quotient and remainder of a and b :",np.divmod(a,b))
print("remainders when a/b :",np.remainder(a,b))

division of a and b : [5.         6.66666667 7.5       ]
floor_division of a and b : [5 6 7]
mod of a and b : [0 2 2]
quotient and remainder of a and b : (array([5, 6, 7], dtype=int32), array([0, 2, 2], dtype=int32))
remainders when a/b : [0 2 2]


In [68]:
a

array([10, 20, 30])

In [69]:
a.sum()

60

In [70]:
a = np.array([[1,2],[5,6]])
a.sum()

14

In [71]:
a.sum(axis=0)

array([6, 8])

In [72]:
a.sum(axis=1)

array([ 3, 11])


- Trigonometric Functions

In [73]:
x = np.sin(np.pi/2)

print(x)

1.0


In [74]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)
x

array([1.        , 0.8660254 , 0.70710678, 0.58778525])

In [75]:
arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [76]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


- Logarithmic and Exponential Functions

In [ ]:
exp(arr)	Returns exponential of an input array element wise
expm1(arr)	Returns exponential exp(x)-1 of an input array element wise
exp2(arr)	Returns exponential 2**x of all elements in an array
log(arr)	Returns natural log of an input array element wise
log10(arr)	Returns log base 10 of an input array element wise
log2(arr)	Returns log base 2 of an input array element wise
logaddexp(arr)	Returns logarithm of the sum of exponentiations of all inputs
logaddexp2(arr)	Returns logarithm of the sum of exponentiations of the inputs in base 2

In [77]:
import numpy as np
a = np.array([1,2,3,4,5])
a_log = np.log(a)
a_exp = np.exp(a)
print("log of input array a is:",a_log)
print("exponent of input array a is:",a_exp)


log of input array a is: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
exponent of input array a is: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


- Rounding Functions

In [ ]:
around(arr,decimal)	Rounds the elements of an input array upto given decimal places
round_(arr,decimal)	Rounds the elements of an input array upto given decimal places
rint(arr)	Round the elements of an input array to the nearest integer towards zero
fix(arr)	Round the elements of an input array to the nearest integer towards zero
floor(arr)	Returns floor of input array element wise
ceil(arr)	Returns ceiling of input array element wise
trunc(arr)	Return the truncated value of an input array element wise

In [78]:
a = np.array([1.23,4.165,3.8245])
rounded_a = np.round_(a,2)
print(rounded_a)

[1.23 4.16 3.82]


In [79]:
floor_a = np.floor(a)
print(floor_a)

[1. 4. 3.]


In [80]:
# random concept
from numpy import random


In [81]:
x = random.randint(100) #Generate a random integer from 0 to 100

print(x)

63


In [82]:
x = random.rand()#Generate a random float from 0 to 1

print(x)

0.6208453813479431


In [83]:
x = random.rand(20)#Generate a random float from 0 to 1

print(x)

[0.92480766 0.84028724 0.34393868 0.66386629 0.1048452  0.62863523
 0.80969256 0.8698743  0.48527448 0.42315858 0.91478743 0.83050103
 0.14171911 0.68837616 0.32715996 0.99690457 0.64977601 0.16157658
 0.41178296 0.07967129]


In [101]:
x=random.randint(100, size=(5))#Generate a 1-D array containing 5 random integers from 0 to 100

print(x)

[ 0  4 94  3 87]


In [102]:
x*100

array([   0,  400, 9400,  300, 8700])

In [103]:
x+x

array([  0,   8, 188,   6, 174])

In [ ]:
take for loop example as list and compare with numpy

In [104]:
l = [1,2,3]
l1 = [3,4,5]
s=[]
for i in range(len(l)):
    s.append(l[i]+l1[i])
print(s)
    

        

[4, 6, 8]


In [106]:
l = np.array(l)
l1 = np.array(l1)
l+l1

array([4, 6, 8])

In [85]:
x=random.randint(100)#Generate a 1-D array containing 5 random integers from 0 to 100

print(x)

81


In [86]:
x = random.randint(100, size=(3, 5))#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

print(x)

[[26 51 44 44  3]
 [43 26 30 46 38]
 [56 79 23 77 86]]


In [87]:
x = random.rand(5)#Generate a 1-D array containing 5 random floats

print(x)

[0.29235663 0.50667383 0.34692504 0.94663562 0.03099832]


In [88]:
#Generate a 2-D array with 3 rows, each row containing 5 random numbers:



x = random.rand(3, 5)

print(x)

[[0.89525169 0.82374062 0.574409   0.07028117 0.78250496]
 [0.53592569 0.73681721 0.91187277 0.12456356 0.96498891]
 [0.00809988 0.49566404 0.55574529 0.95047889 0.18747332]]


In [89]:
#Return one of the values in an array:



x = random.choice([3, 5, 7, 9])

print(x)

3


In [90]:
#Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):



x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 5 9 7 9]
 [5 3 7 3 7]
 [9 5 3 7 5]]


In [91]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 5 7 7 5 7 3 3 5 3 7 5 5 7 7 5 3 7 5 7 5 3 7 7 7 3 5 7 7 7 7 7 5 7 7 7 7
 5 5 5 7 7 7 5 7 5 3 5 7 3 7 7 7 7 5 5 5 7 7 7 7 7 7 5 7 7 7 7 7 7 7 7 5 7
 7 5 7 7 7 7 7 7 5 7 5 5 5 5 7 7 7 7 7 7 7 7 5 5 7 3]


In [92]:
#Same example as above, but return a 2-D array with 3 rows, each containing 5 values.



x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)


[[5 5 5 5 7]
 [7 7 7 7 7]
 [5 3 7 7 7]]


In [93]:
#Shuffling Arrays
#Shuffle means changing arrangement of elements in-place. i.e. in the array itself.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[4 3 1 2 5]


In [96]:
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[3 2 1 4 5]


In [95]:
help(np.random.permutation)

Help on built-in function permutation:

permutation(...) method of mtrand.RandomState instance
    permutation(x)
    
    Randomly permute a sequence, or return a permuted range.
    
    If `x` is a multi-dimensional array, it is only shuffled along its
    first index.
    
    Parameters
    ----------
    x : int or array_like
        If `x` is an integer, randomly permute ``np.arange(x)``.
        If `x` is an array, make a copy and shuffle the elements
        randomly.
    
    Returns
    -------
    out : ndarray
        Permuted sequence or array range.
    
    Examples
    --------
    >>> np.random.permutation(10)
    array([1, 7, 4, 3, 0, 9, 2, 5, 8, 6])
    
    >>> np.random.permutation([1, 4, 9, 12, 15])
    array([15,  1,  9,  4, 12])
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random.permutation(arr)
    array([[6, 7, 8],
           [0, 1, 2],
           [3, 4, 5]])

